name: nector
description: "A HTTP inspector tool to analyse the network calls in a flutter app."
version: 1.1.0
homepage: "https://github.com/dartcoders/nector"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  rxdart: ^0.28.0
  dio: ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.dartcoders.nector
        pluginClass: NectorPlugin
      ios:
        pluginClass: NectorPlugin
